### ISSUE TITLE
Start a wiki for the project

### ISSUE THREAD

**Issue by infomaven** [infomaven/team11#3]
This is a place where we can share information, process and "how to" instructions for using tools (like GitHub).

**Comment by kdv24** [comment]
I'm not sure what format or template or site you're thinking for this?  Are you thinking kind of like another README style file?  If someone can just create a shell for me to place the info into, I'm happy to share what I've found for how to get us going on github. I'm playing around with it now, so can let you know what I come up with.  

Also, I'm creating a hipchat account for us to use for easier communication.  It looks to be available as a web app, mobile app (android and iOS), and as web site, so seems like it would be easy for every body.  And, it would prevent things like me typing this in the "Start a wiki" section.  :)

**Comment by infomaven** [comment]
Yes, GitHub provides a lot of built-in functionality for maintaining a wiki along with the source code, and I think this would be a good way to share knowledge and document our project requirements, designs, etc. 
Thanks for setting up the HipChat account. We have this at work, but I have not used it much because I tend to use email, issue tickets and IM more often to communicate with teammates,  but it looks rather promising. 
- Nadine

Date: Sat, 21 Feb 2015 19:20:43 -0800

**Comment by infomaven** [comment]
Looks like you got it! Thanks for your wiki contribution and pull request. 
https://github.com/infomaven/team11/wiki/How-to-use-Git-as-a-group
