### ISSUE TITLE
Add other team member as collaborators

### ISSUE THREAD

**Issue by kdv24** [infomaven/team11#6]
Hey Nadine,

Would you please add us as collaborators on this?  I think you can do it in the setting section, but we can't access it (as far as I know).

Thanks!

**Comment by infomaven** [comment]
Hi Kelly: 
I added you, Monique and Meredith as collaborators while we were at the hack event. 
You should have rights to push changes to the repo and edit the wiki (at least that's what the webpage says).

If you're not able to do things, we should take a look at this next time we meet in person. 

![screen shot 2015-03-13 at 7 36 22 pm](https://cloud.githubusercontent.com/assets/3871363/6649984/629ddcce-c9b8-11e4-8680-da5580580d29.png)

**Comment by kdv24** [comment]
Ok, let's look at it tomorrow.

**Comment by kdv24** [comment]
https://www.hipchat.com/invite/285751/e6934e26eed772249972e7159b96f995 https://www.hipchat.com/invite/285751/e6934e26eed772249972e7159b96f995
